/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package data.services.code.challenge;

import org.junit.Test;

/**
 * This is Server Test class for testing 
 * @author prgundu
 *
 */
public class DataServicesServerTest {
	
	private static final String IP_ADDRESS = "127.0.0.1";
	private static final int PORT = 4000;
	
	@Test
	public void client1Test() {
		DataServicesClient client1 = new DataServicesClient(IP_ADDRESS, PORT);
		client1.sendGeneratedRandomNumbersToServer();
		client1.stopConnection();
	}
	
	@Test
	public void client2Test() {
		DataServicesClient client = new DataServicesClient(IP_ADDRESS, PORT);
		client.stopConnection();
	}
	
	@Test
	public void client3Test() {
		DataServicesClient client = new DataServicesClient(IP_ADDRESS, PORT);
		client.stopConnection();
	}
	
	@Test
	public void client4Test() {
		DataServicesClient client = new DataServicesClient(IP_ADDRESS, PORT);
		client.stopConnection();
	}
	
	@Test
	public void client5Test() {
		DataServicesClient client = new DataServicesClient(IP_ADDRESS, PORT);
		client.terminate();
		client.stopConnection();
	}
}
